// ── tests/ledger-plan.js ──────────────────────────────────────────────────
// Apsara, 2026-10-08, on what the QuickBooks agent should be able to do:
//
//   "you can even tell like remove this container from the <billno> billed
//    on 30-dec-25 and add this container by creating a new bill <bill> on
//    3-jan-26 and then match it with this payment(partial/full)"
//
// Section A is that sentence, as a plan, end to end.
//
// ── WHAT THIS FILE IS REALLY DEFENDING ──────────────────────────────────
// Everything else is the plan being WRONG, because that is the whole job.
// A language model proposes; this verifier is the only thing between a
// plausible-looking plan and her ledger. The research she asked for says
// the same in one line — VerAct's two-layer argument is that plans are
// generated by statistical pattern matching, so a plan can read perfectly
// and still violate an invariant, and the verifier must therefore be
// symbolic rather than another model.
//
// So the checks that matter are the refusals, and in particular the ones
// where each STEP is individually fine and the SEQUENCE is not.
//
// No model is called anywhere in this file. That is the design.

const fs = require('fs');
const os = require('os');
const path = require('path');

let pass = 0, fail = 0;
const failures = [];
const ck = (label, ok, detail) => {
    if (ok) { pass += 1; console.log('  PASS  ' + label); }
    else { fail += 1; failures.push(label); console.log('  FAIL  ' + label); if (detail) console.log('        ' + detail); }
};
const section = (t) => console.log('\n=== ' + t + ' ===');

const TMP = fs.mkdtempSync(path.join(os.tmpdir(), 'jarvis-plan-'));
process.env.DATA_DIR = TMP;
process.env.JARVIS_TEST = '1';
const ROOT = path.join(__dirname, '..');
const P = require(path.join(ROOT, 'helpers/ledgerPlan'));

// Her world, small enough to reason about by hand.
const WORLD = () => ({
    bills: [
        { id: 'BILL_914', supplier: 'Hugo', date: '2025-12-30', containers: ['TGHU1234567'], amount: 41285 },
        { id: 'BILL_915', supplier: 'Mario', date: '2026-01-02', containers: ['MSKU7654321'], amount: 10000 },
    ],
    payments: [
        { id: 'PAY_77', party: 'Hugo', date: '2026-01-05', amount: 25000, applied: [] },
        // Part-applied on purpose: 5,000 received, 3,000 already against
        // BILL_914, so 2,000 is free. My first version applied the whole
        // 5,000 and then asserted the remainder could be spent — a fixture
        // that contradicted the check it was written for.
        { id: 'PAY_78', party: 'Hugo', date: '2026-01-09', amount: 5000,
          applied: [{ bill_id: 'BILL_914', amount: 3000 }] },
    ],
});

// ── A — HER SENTENCE, END TO END ─────────────────────────────────────────
{
    section('A — her sentence, as a plan');
    // "remove this container from BILL_914 billed on 30-dec-25, add it by
    //  creating a new bill on 3-jan-26, then match it with PAY_77 partial"
    const plan = [
        { op: 'detach-container', bill_id: 'BILL_914', container_no: 'TGHU1234567' },
        { op: 'create-bill', supplier: 'Hugo', date: '2026-01-03', container_no: 'TGHU1234567' },
        { op: 'match-payment', payment_id: 'PAY_77', bill_id: '#2', amount: 12000 },
    ];
    const v = P.verify(plan, WORLD());
    ck('the whole sentence verifies', v.ok === true, JSON.stringify(v.problems));

    const said = P.describe(plan);
    ck('  and reads back in words, not JSON',
       /take container TGHU1234567 off bill BILL_914/.test(said[0].says)
       && /create a bill for Hugo dated 2026-01-03/.test(said[1].says), JSON.stringify(said));

    // ── THE PART THAT MAKES IT APPROVABLE ────────────────────────────────
    // "3 operations succeeded" is not a confirmation. What she acts on is
    // what each supplier is owed, so that is what the preview is.
    const d = v.simulation.diff;
    const hugo = d.find((r) => r.supplier === 'Hugo');
    ck('the preview is per supplier, not per operation', !!hugo, JSON.stringify(d));
    ck('  Hugo gains a bill', hugo.bills.before === 1 && hugo.bills.after === 2,
       JSON.stringify(hugo.bills));
    ck('  and 12,000 more of his payments is applied',
       hugo.paid.change === 12000, JSON.stringify(hugo.paid));
    ck('  while the container count is unchanged — it moved, it did not multiply',
       hugo.containers.before === hugo.containers.after, JSON.stringify(hugo.containers));
    ck('  and Mario, who was not mentioned, is not in the diff at all',
       !d.find((r) => r.supplier === 'Mario'), JSON.stringify(d.map((r) => r.supplier)));

    // partial AND full, both words she used
    const full = P.verify([...plan.slice(0, 2),
        { op: 'match-payment', payment_id: 'PAY_77', bill_id: '#2', amount: 25000 }], WORLD());
    ck('a FULL match of the payment also verifies', full.ok === true, JSON.stringify(full.problems));
}

// ── B — EACH STEP FINE, THE SEQUENCE NOT ─────────────────────────────────
// The dangerous class. A per-step validator passes all of these.
{
    section('B — where only the sequence is wrong');

    // Attach without detaching. Every step is individually legal.
    const twice = P.verify([
        { op: 'create-bill', supplier: 'Hugo', date: '2026-01-03' },
        { op: 'attach-container', bill_id: '#1', container_no: 'TGHU1234567' },
    ], WORLD());
    ck('a container cannot be put on a second bill while still on the first',
       twice.ok === false && /billed twice/.test(JSON.stringify(twice.problems)),
       JSON.stringify(twice.problems));

    // Detach and never re-attach. This is the half-finished generation, and
    // it UNDERSTATES her costs, which is the direction nobody questions.
    const orphan = P.verify([
        { op: 'detach-container', bill_id: 'BILL_914', container_no: 'TGHU1234567' },
    ], WORLD());
    ck('a container taken off every bill is refused',
       orphan.ok === false && /no bill at all/.test(JSON.stringify(orphan.problems)),
       JSON.stringify(orphan.problems));
    ck('  and the reason says its cost would disappear',
       /disappear from the books/.test(JSON.stringify(orphan.problems)));

    // Two matches, each within the payment, together over it.
    const over = P.verify([
        { op: 'match-payment', payment_id: 'PAY_77', bill_id: 'BILL_914', amount: 20000 },
        { op: 'match-payment', payment_id: 'PAY_77', bill_id: 'BILL_915', amount: 20000 },
    ], WORLD());
    ck('two matches that each fit but together overpay are refused',
       over.ok === false && /left unapplied/.test(JSON.stringify(over.problems)),
       JSON.stringify(over.problems));

    // Already partly applied elsewhere — the remainder is what is free.
    const rest = P.verify([
        { op: 'match-payment', payment_id: 'PAY_78', bill_id: 'BILL_915', amount: 1000 }], WORLD());
    ck('a payment already part-applied can still spend its remainder', rest.ok === true,
       JSON.stringify(rest.problems));
    const tooMuch = P.verify([
        { op: 'match-payment', payment_id: 'PAY_78', bill_id: 'BILL_915', amount: 2500 }], WORLD());
    ck('  but not more than the remainder — 2,000 of 5,000 is left',
       tooMuch.ok === false && /2000\.00 left unapplied/.test(JSON.stringify(tooMuch.problems)),
       JSON.stringify(tooMuch.problems));
}

// ── C — IDS IT MADE UP, AND REFERENCES ───────────────────────────────────
// The commonest way these plans go wrong is a confident, invented id.
{
    section('C — it may not invent a record');
    const ghost = P.verify([{ op: 'detach-container', bill_id: 'BILL_999', container_no: 'X' }], WORLD());
    ck('a bill that does not exist is refused by name',
       ghost.ok === false && /no bill BILL_999/.test(JSON.stringify(ghost.problems)),
       JSON.stringify(ghost.problems));
    ck('a payment that does not exist is refused',
       P.verify([{ op: 'match-payment', payment_id: 'PAY_X', bill_id: 'BILL_914', amount: 1 }],
           WORLD()).ok === false);

    // #1 means "whatever step 1 creates" — so the model never has to guess
    // an id for a record that does not exist yet, which is the situation
    // that produces invented ones.
    const forward = P.verify([
        { op: 'match-payment', payment_id: 'PAY_77', bill_id: '#2', amount: 100 },
        { op: 'create-bill', supplier: 'Hugo', date: '2026-01-03', container_no: 'TGHU1234567' },
    ], WORLD());
    ck('a reference to a step that has not happened yet is refused',
       forward.ok === false && /has not happened yet/.test(JSON.stringify(forward.problems)),
       JSON.stringify(forward.problems));
    const wrongRef = P.verify([
        { op: 'detach-container', bill_id: 'BILL_914', container_no: 'TGHU1234567' },
        { op: 'match-payment', payment_id: 'PAY_77', bill_id: '#1', amount: 100 },
    ], WORLD());
    ck('  and a reference to a step that creates nothing is refused',
       wrongRef.ok === false && /not a step that creates a bill/.test(JSON.stringify(wrongRef.problems)),
       JSON.stringify(wrongRef.problems));
}

// ── D — THE VOCABULARY IS THE BOUNDARY ───────────────────────────────────
{
    section('D — it can only propose what Jarvis will do');
    ck('an operation outside the vocabulary is refused',
       P.verify([{ op: 'rewrite-history', bill_id: 'BILL_914' }], WORLD()).ok === false);

    // ── DELETE IS IN, AND IT IS HERS ─────────────────────────────────────
    // I left it out and asserted here that the vocabulary had none, on the
    // argument that accounting corrects by reversing. Apsara, 2026-10-08:
    // "add delete option". Her ledger, her call — and the argument was
    // never that delete is unthinkable, since ledgerBulkDelete.js has
    // existed since 2026-09-29 because she asked for it then as well.
    //
    // What survives of the argument is the two guards below, which are the
    // same two that file already enforces.
    ck('delete IS in the vocabulary — her decision, 2026-10-08',
       !!P.OPS['delete-bill'], Object.keys(P.OPS).join(', '));

    // A field the executor would ignore is worse than a rejected one: the
    // plan says something that will not happen, and the preview agrees
    // with the plan rather than with reality.
    const extra = P.verify([{ op: 'create-bill', supplier: 'Hugo', date: '2026-01-03',
        approve: true, bypass_checks: true }], WORLD());
    ck('a field the executor would ignore is refused, not dropped',
       extra.ok === false && /silently ignored/.test(JSON.stringify(extra.problems)),
       JSON.stringify(extra.problems));

    ck('a date that is not YYYY-MM-DD is refused',
       P.verify([{ op: 'create-bill', supplier: 'Hugo', date: '3-jan-26' }], WORLD()).ok === false);
    ck('a match of zero is refused',
       P.verify([{ op: 'match-payment', payment_id: 'PAY_77', bill_id: 'BILL_914', amount: 0 }],
           WORLD()).ok === false);
    ck('an empty plan is refused', P.verify([], WORLD()).ok === false);
    ck('every problem names the step it came from',
       P.verify([{ op: 'nonsense' }], WORLD()).problems.every((p) => typeof p.step === 'number'));
}

// ── D2 — DELETE, AND THE TWO THINGS IT MUST NOT DO ───────────────────────
{
    section('D2 — deleting a bill');
    const plain = P.verify([
        { op: 'detach-container', bill_id: 'BILL_915', container_no: 'MSKU7654321' },
        { op: 'attach-container', bill_id: 'BILL_914', container_no: 'MSKU7654321' },
        { op: 'delete-bill', bill_id: 'BILL_915' },
    ], WORLD());
    ck('a bill emptied of its container can be deleted', plain.ok === true,
       JSON.stringify(plain.problems));

    // ── ORPHANED MONEY, THE FAILURE THAT HIDES ───────────────────────────
    // ledgerBulkDelete.js's header names it: a payment reaches a bill
    // through its allocations, so deleting the bill leaves the payment
    // pointing at an id nothing answers to. The money left the account and
    // belongs to no container — and it shows as missing nowhere.
    const paid = P.verify([
        { op: 'detach-container', bill_id: 'BILL_914', container_no: 'TGHU1234567' },
        { op: 'attach-container', bill_id: 'BILL_915', container_no: 'TGHU1234567' },
        { op: 'delete-bill', bill_id: 'BILL_914' },
    ], WORLD());
    ck('a bill with a payment against it is NOT deleted', paid.ok === false,
       JSON.stringify(paid.problems));
    ck('  and it names the payment and says to unmatch it first',
       /PAY_78/.test(JSON.stringify(paid.problems)) && /unmatch/.test(JSON.stringify(paid.problems)),
       JSON.stringify(paid.problems));

    // Deleting a bill that still holds a container would make that
    // container's cost disappear. The plan-wide check catches it, so a
    // delete is allowed when the plan re-homes the container and refused
    // when it does not — which is the difference between a correction and
    // a quiet loss.
    const withCargo = P.verify([{ op: 'delete-bill', bill_id: 'BILL_915' }], WORLD());
    ck('a bill still holding a container is NOT deleted', withCargo.ok === false,
       JSON.stringify(withCargo.problems));
    ck('  because the container would end up on no bill',
       /no bill at all|disappear from the books/.test(JSON.stringify(withCargo.problems)));
}

// ── D3 — EVERY CHANGE IS WRITTEN DOWN, AND EVERY CHANGE HAS AN UNDO ──────
// Apsara, 2026-10-08: "make it log every change we are doing in qb/books so
// that we can check it later."
{
    section('D3 — the log entry, and the undo');
    const plan = [
        { op: 'detach-container', bill_id: 'BILL_914', container_no: 'TGHU1234567' },
        { op: 'create-bill', supplier: 'Hugo', date: '2026-01-03', container_no: 'TGHU1234567' },
        { op: 'match-payment', payment_id: 'PAY_77', bill_id: '#2', amount: 12000 },
    ];
    const v = P.verify(plan, WORLD());
    const rec = P.auditRecord({ asked: 'move TGHU1234567 off BILL_914 onto a new bill on 3 Jan and match 12000 of PAY_77',
        plan, verification: v, actor: 'apsara' });

    ck('the entry keeps HER WORDS, not only the plan',
       /move TGHU1234567 off BILL_914/.test(rec.asked), rec.asked);
    ck('  and the plan, so the reading can be judged against the sentence',
       rec.plan.length === 3 && rec.steps.length === 3);
    ck('  and the figures as they were at the time',
       Array.isArray(rec.diff) && rec.diff.some((r) => r.supplier === 'Hugo'));
    ck('  and who asked', rec.actor === 'apsara');

    // A refused plan must not carry a diff — a diff reads as something
    // that happened.
    const refused = P.auditRecord({ asked: 'x', plan: [{ op: 'nope' }],
        verification: P.verify([{ op: 'nope' }], WORLD()) });
    ck('a refused plan is logged WITHOUT a diff',
       refused.ok === false && refused.diff === null && refused.problems.length > 0,
       JSON.stringify(refused.problems));

    // ── AND THE REFUSAL THAT HAPPENS *DURING* SIMULATION ─────────────────
    // The check above uses a plan that fails before simulation starts, so
    // there is no diff to leak and it passes however the code is written —
    // the mutation "a refused plan is logged with a diff" survived it.
    // This one gets as far as a simulated world and is refused there, so a
    // diff genuinely exists and must still be withheld. A diff on a
    // refused plan reads as something that happened.
    const orphanPlan = [{ op: 'detach-container', bill_id: 'BILL_914', container_no: 'TGHU1234567' }];
    const orphanV = P.verify(orphanPlan, WORLD());
    ck('  the simulated-and-refused case really does produce a diff',
       orphanV.ok === false && !!orphanV.simulation && orphanV.simulation.diff.length > 0,
       JSON.stringify(orphanV.problems));
    const orphanRec = P.auditRecord({ asked: 'take it off', plan: orphanPlan, verification: orphanV });
    ck('  and the log still withholds it', orphanRec.diff === null, JSON.stringify(orphanRec.diff));

    // ── THE UNDO, IN REVERSE ORDER ───────────────────────────────────────
    // Undoing the detach before undoing the attach would put the container
    // on two bills on the way back, and the verifier would refuse its own
    // undo. So the order is the part worth asserting.
    const rev = P.reverseOf(plan, { '#2': 'BILL_NEW_1' });
    ck('the undo is the plan backwards', rev.length === 3);
    ck('  unapplying the payment first', rev[0].op === 'unmatch-payment', JSON.stringify(rev[0]));
    ck('  then deleting the bill it created', rev[1].op === 'delete-bill'
       && rev[1].bill_id === 'BILL_NEW_1', JSON.stringify(rev[1]));
    ck('  then putting the container back where it was',
       rev[2].op === 'attach-container' && rev[2].bill_id === 'BILL_914', JSON.stringify(rev[2]));
    ck('  and the real id is used, not the #2 placeholder',
       !JSON.stringify(rev).includes('"#2"'), JSON.stringify(rev));

    // Un-deleting is a RESTORE, not a create: the bill had an id, a history
    // and its own fields. Re-creating it would make a different record
    // wearing the same supplier's name.
    const undel = P.reverseOf([{ op: 'delete-bill', bill_id: 'BILL_915' }]);
    ck('undoing a delete is a restore, never a re-create',
       undel[0].op === 'restore-bill', JSON.stringify(undel));
}

// ── E — IT CHANGES NOTHING ───────────────────────────────────────────────
// The whole value of layers 3 and 4 is that they can be run on a plan
// before it is real. A verifier that writes is not a verifier.
{
    section('E — verifying is not doing');
    const w = WORLD();
    const snapshot = JSON.stringify(w);
    P.verify([
        { op: 'detach-container', bill_id: 'BILL_914', container_no: 'TGHU1234567' },
        { op: 'create-bill', supplier: 'Hugo', date: '2026-01-03', container_no: 'TGHU1234567' },
        { op: 'match-payment', payment_id: 'PAY_77', bill_id: '#2', amount: 12000 },
    ], w);
    ck('the world it was given is untouched', JSON.stringify(w) === snapshot);
    const before = fs.readdirSync(TMP).length;
    ck('  and nothing was written to disk', fs.readdirSync(TMP).length === before);
    const src = fs.readFileSync(path.join(ROOT, 'helpers/ledgerPlan.js'), 'utf8');
    ck('  and the module calls no model and no store',
       !/gemini|mutateJson|loadJson|fetch\(/.test(src));
}

console.log(`\n  ${pass} passed, ${fail} failed`);
if (failures.length) { console.log('\n  failed:'); failures.forEach((f) => console.log('    · ' + f)); }
try { fs.rmSync(TMP, { recursive: true, force: true }); } catch (e) {}
process.exit(fail ? 1 : 0);
